### PR TITLE
Upload autodistill classification notebook

### PR DESCRIPTION
**Pull request by capjamesg**
This PR adds the accompanying notebook for our [Train an Image Classification Model with No Labeling](https://blog.roboflow.com/train-classification-model-no-labeling/) tutorial.

### CODE REVIEW

**Comment by SkalskiP** [comment]
It looks like you have a typo in the file name `how-to-train-yolov8-classification-no_-abeling.ipynb`. I assume you aimed for `how-to-train-yolov8-classification-no-abeling.ipynb`

**Comment by SkalskiP** [comment]
It also looks like you forgot to edit `README.md`.

**Comment by SkalskiP** [comment]
Hi @capjamesg 👋🏻 Please accept the CLA and resolve the comment I left last time. So we could merge this PR.

**Comment by capjamesg** [comment]
Responded to all feedback ✅

**Review by SkalskiP — APPROVED** [review]

**Pull request merged**
