### PR TITLE
update yolov8 instance segmentation notebook

### PR DESCRIPTION
**Pull request by artyaltanzaya**
## Type of change

- updated yolov8 instance segmentation notebook

### CODE REVIEW

**Comment by SkalskiP** [comment]
Hi @artyaltanzaya 👋🏻 ! Could you give us a bit deeper description for this PR?

**Comment by artyaltanzaya** [comment]
Running inference on different dataset of car parts since video dataset on coral segmentation was deleted from roboflow universe.

**Comment by artyaltanzaya** [comment]
Added ["How to Train Yolov8 with SAM notebook"](https://blog.roboflow.com/how-to-use-yolov8-with-sam/)

**Comment by capjamesg** [comment]
Does this PR require action @artyaltanzaya?

**Comment by artyaltanzaya** [comment]
@SkalskiP Solved conflicts!

**Pull request merged**
