### PR TITLE
Add autodistill segmentation notebook

### PR DESCRIPTION
**Pull request by capjamesg**
This PR adds the notebook used in our [Autodistill segmentation blog tutorial](https://blog.roboflow.com/train-a-segmentation-model-no-labeling/).

### CODE REVIEW

**Comment by SkalskiP** [comment]
Same [comments](https://github.com/roboflow/notebooks/pull/161#issuecomment-1620224823) as for #161.

**Comment by capjamesg** [comment]
@SkalskiP I have responded to your feedback in my latest commits.

**Comment by SkalskiP** [comment]
Same story here... Notebook throws an exception.

Screenshot 2023-07-05 at 12 49 22

**Comment by capjamesg** [comment]
Same thing again. I trained four different models in the notebook so I'll need to substitute `train4` with `train`. Will submit a new commit.

**Comment by SkalskiP** [comment]
@capjamesg please submit PR with working notebook.

**Comment by SkalskiP** [comment]
@capjamesg It still doesn't work...

Screenshot 2023-07-07 at 18 33 15

**Comment by SkalskiP** [comment]
Hi @capjamesg 👋🏻 Please accept the CLA and resolve the comment I left last time. So we could merge this PR.

**Comment by capjamesg** [comment]
@SkalskiP I have responded to all of your feedback in the notebook in my latest commit.

**Comment by capjamesg** [comment]
@SkalskiP The output lines have been removed from the notebook.

**Comment by SkalskiP** [comment]
@capjamesg looks like we could merge. Could you resolve the conflicts?

**Comment by capjamesg** [comment]
@SkalskiP Done! I'll let you merge when you are ready.

**Review by SkalskiP — APPROVED** [review]

**Pull request merged**
