### PR TITLE
Add explore more Roboflow open source projects section

### PR DESCRIPTION
**Pull request by capjamesg**
This PR adds a new standard "explore more Roboflow open source projects" to the project README.

### CODE REVIEW

**Comment by SkalskiP** [comment]
Hi, @capjamesg could we do it the same way we do it in `supervision`?

**Comment by capjamesg** [comment]
That's the plan! Let's figure it out in supervision then I'll make the change.

**Comment by SkalskiP** [comment]
Awesome! I merged `supervision` already, so it should be way easier now :)

**Comment by capjamesg** [comment]
Replaced with https://github.com/roboflow/notebooks/pull/195.

**Pull request closed without merging**
