### PR TITLE
Package blog post

### PR DESCRIPTION
**Pull request by andrew-healey**
This PR adds the notebook from the blog post [Train a Package Detector with Two Labeled Images](https://blog.roboflow.com/package-detector/).

### CODE REVIEW

**Comment by SkalskiP** [comment]
Hi, @andrew-healey 👋🏻! Apologies. I didn't notice that PR before. Would you be so king as to accept CLA? That will allow us to process this PR.

**Comment by andrew-healey** [comment]
Signed!

**Comment by capjamesg** [comment]
The [live notebook](https://colab.research.google.com/drive/1ZGPZ7aWHsLQIXF5HaSiScwZAi2UfSXos?ref=blog.roboflow.com) looks good to me so I will merge this.

**Review by capjamesg — APPROVED** [review]
The [live notebook](https://colab.research.google.com/drive/1ZGPZ7aWHsLQIXF5HaSiScwZAi2UfSXos?ref=blog.roboflow.com) looks good to me so I will merge this.

**Pull request merged**
